#pragma once

#ifndef TSUKUYOMI_VERSION
#define TSUKUYOMI_VERSION "0.0.0"
#endif

#define TSUKUYOMI_WIDEN_IMPL(text) L##text
#define TSUKUYOMI_WIDEN(text) TSUKUYOMI_WIDEN_IMPL(text)
#define TSUKUYOMI_VERSION_W TSUKUYOMI_WIDEN(TSUKUYOMI_VERSION)
